name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            export NVM_DIR=~/root/.nvm
            source ~/.nvm/nvm.sh
            cd /home/react-spa-deploy
            ls -la
            git pull
            npm install
            npm run build
            cp ./dist /var/www/html
      - name: On Failure
        if: failure()
        uses: hunghg255/action-notifications@master
        with:
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}

  notifification:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: hunghg255/action-notifications@master
        if: always()
        with:
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "React DEVELOPMENT"
          description: "Test here: https://google.com"
